using McTools.Xrm.Connection;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using XrmToolBox.Extensibility;
using DataModelDevOpsExtractor.Service;
using DataModelDevOpsExtractor.Model;
using DataModelDevOpsExtractor.Repository;

namespace DataModelDevOpsExtractor
{
    public partial class PluginControl : MultipleConnectionsPluginControlBase
    {
        // Proprietà richieste da MultipleConnectionsPluginControlBase
        public new IOrganizationService Service { get; set; }
        public new ConnectionDetail ConnectionDetail { get; set; }
        public new event EventHandler OnRequestConnection;
        public new event EventHandler OnCloseTool;
        public new event EventHandler OnWorkAsync;
        private string dataModelEnvConnectionString = string.Empty;
        private string lastGeneratedMarkdownTemplate = string.Empty;
        private bool isMarkdownTemplateAutoGenerated;
        private UploadProgressService uploadProgressService;

        public PluginControl()
        {
            InitializeComponent();
            uploadProgressService = new UploadProgressService(progressBarUploadAmbiente, lblUploadProgress);
            MarkdownUtilitiesService.ConfigureMarkdownEditorAppearance(txtMarkdown);
            HideUploadSummary();
            ResetUploadProgress();
            // Carica la connection string e la datamodeluri salvate
            txtConnectionString.Text = UserConfig.LoadConnectionString();
            txtPrefix.Text = UserConfig.LoadPrefix();
        }
        private void ToolStripBtnDataModelEnv_Click(object sender, EventArgs e)
        {
            HideUploadProgressForOtherAction();
            AddAdditionalOrganization();

            if (this.AdditionalConnectionDetails.Count == 0)
            {
                return;
            }

            if (this.AdditionalConnectionDetails != null && this.AdditionalConnectionDetails.Count > 1)
                this.RemoveAdditionalOrganization(this.AdditionalConnectionDetails[0]);

            toolStripBtnDataModelEnv.Text = $"Data Model Env: {this.AdditionalConnectionDetails[0].ConnectionName}";
        }
        private void BtnSave_Click(object sender, EventArgs e)
        {
            HideUploadProgressForOtherAction();
            UserConfig.SaveConnectionString(txtConnectionString.Text.Trim());
            UserConfig.SavePrefix(txtPrefix.Text.Trim());
            MessageBox.Show("Configurazioni salvate.");
        }

        private async void BtnExtract_Click(object sender, EventArgs e)
        {
            HideUploadProgressForOtherAction();
            btnExtract.Enabled = false;
            try
            {
                var dataModelService = new DataModelService(); 
                var allRows = await dataModelService.getDataModelRows(
                    txtConnectionString.Text.Trim(),
                    txtTaskIds.Text.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                );
                // Header CSV
                string[] headers = new[] {
                    "System","Table","Schema name","Display name (IT)","Display name (EN)","Description","Column type","Lookup table","Additional data","Requirement level"
                };

                // Salva il file CSV nella cartella Data
                var dataDir = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Data");
                if (!System.IO.Directory.Exists(dataDir))
                    System.IO.Directory.CreateDirectory(dataDir);
                var filePath = System.IO.Path.Combine(dataDir, $"DataModel_{DateTime.Now:yyyyMMdd_HHmmss}.csv");

                using (var writer = new System.IO.StreamWriter(filePath, false, Encoding.UTF8))
                {
                    writer.WriteLine(string.Join(";", headers));
                    foreach (var row in allRows)
                    {
                        var cleaned = row.Select(cell =>
                            System.Text.RegularExpressions.Regex.Replace(
                                System.Net.WebUtility.HtmlDecode(cell ?? ""),
                                "[\u00A0\u200B\u200C\u200D\uFEFF]", // spazi non standard e caratteri invisibili
                                " "
                            ).Replace("\n", " ").Replace("\r", " ").Replace(";", ",").Trim()
                        ).ToArray();
                        writer.WriteLine(string.Join(";", cleaned));
                    }
                }

                MessageBox.Show($"File CSV creato: {filePath}");
                System.Diagnostics.Process.Start("explorer.exe", dataDir);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Errore: {ex.Message}");
            }
            finally
            {
                btnExtract.Enabled = true;
            }
        }

        public override void UpdateConnection(IOrganizationService newService, ConnectionDetail detail, string actionName, object parameter)
        {
            Service = newService;
            ConnectionDetail = detail;
            base.UpdateConnection(newService, detail, actionName, parameter);

            UpdateMainConnectionButtonLabel();
            _ = TryPopulateMarkdownTemplateFromPrimaryConnectionAsync();
        }
        public override void ClosingPlugin(XrmToolBox.Extensibility.PluginCloseInfo info) { }

        private void btnSave_Click(object sender, EventArgs e)
        {
            HideUploadProgressForOtherAction();
            try
            {
                var connStr = txtConnectionString.Text.Trim();
                var prefix = txtPrefix.Text.Trim();
                var dataDir = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Data");
                if (!System.IO.Directory.Exists(dataDir))
                    System.IO.Directory.CreateDirectory(dataDir);
                var filePath = System.IO.Path.Combine(dataDir, "connection.txt");
                var uriPath = System.IO.Path.Combine(dataDir, "datamodeluri.txt");
                System.IO.File.WriteAllText(filePath, connStr);
                UserConfig.SaveConnectionString(connStr);
                UserConfig.SavePrefix(prefix);
                MessageBox.Show($"Connection string salvata in: {filePath}");
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Errore nel salvataggio: {ex.Message}");
            }
        }
        protected override void ConnectionDetailsUpdated(NotifyCollectionChangedEventArgs e)
        {
            return;
        }

        private async void buttonUploadDataModel_Click(object sender, EventArgs e)
        {
            HideUploadSummary();
            ResetUploadProgress();
            buttonUploadDataModel.Enabled = false;
            SetUploadProgress(0, "Avvio upload");

            try
            {
                if (!CanStartUploadWithCurrentMarkdown())
                {
                    ResetUploadProgress();
                    return;
                }

                // Usa la seconda connection string (Data Model Env)
                var dataModelEnvConnection = this.AdditionalConnectionDetails;
                if (dataModelEnvConnection.FirstOrDefault() == null)
                {
                    MessageBox.Show("Connection string Data Model Env mancante. Configurala prima dal menu.");
                    ResetUploadProgress();
                    return;
                }

                var dataModelCrmService = dataModelEnvConnection.FirstOrDefault()?.GetCrmServiceClient();
                var completedWithoutErrors = await UploadDataModelToConnection(dataModelCrmService, "Data Model Env");
                if (!completedWithoutErrors)
                {
                    ResetUploadProgress();
                }
            }
            catch (Exception ex)
            {
                ResetUploadProgress();
                MessageBox.Show($"Errore durante l'upload su Data Model Env: {ex.Message}");
            }
            finally
            {
                buttonUploadDataModel.Enabled = true;
            }
        }

        private async void buttonUploadAmbiente_Click(object sender, EventArgs e)
        {
            if (!CanStartUploadWithCurrentMarkdown())
            {
                return;
            }

            HideUploadSummary();
            ResetUploadProgress();
            buttonUploadAmbiente.Enabled = false;
            SetUploadProgress(0, "Avvio upload");

            try
            {
                if (Service == null)
                {
                    MessageBox.Show("Connessione Ambiente mancante. Connettiti all'ambiente prima di eseguire l'upload.");
                    ResetUploadProgress();
                    return;
                }

                var completedWithoutErrors = await UploadDataModelToEnvConnection(Service, "Ambiente", txtSolutionName.Text.Trim());
                if (!completedWithoutErrors)
                {
                    ResetUploadProgress();
                }
            }
            catch (Exception ex)
            {
                ResetUploadProgress();
                MessageBox.Show($"Errore durante l'upload su Ambiente: {ex.Message}");
            }
            finally
            {
                buttonUploadAmbiente.Enabled = true;
            }
        }

        private async Task<bool> UploadDataModelToConnection(IOrganizationService targetService, string targetName)
        {
            if (targetService == null)
            {
                MessageBox.Show($"Connessione target non disponibile: {targetName}.");
                return false;
            }

            var prefixEnv = MarkdownUtilitiesService.NormalizePrefix(txtPrefix.Text);
            if (string.IsNullOrWhiteSpace(prefixEnv))
            {
                MessageBox.Show("Prefix mancante. Inserisci il prefix e salva le configurazioni.");
                return false;
            }

            var dataModelService = new DataModelService();
            var allRows = dataModelService.ParseDataModelMarkdown(txtMarkdown.Text, prefixEnv);
            if (allRows == null || allRows.Count == 0)
            {
                MessageBox.Show("Markdown vuoto o non valido. Premi Load Markdown e verifica il contenuto prima di caricare.");
                return false;
            }

            SetUploadProgress(5, "Validazione dati");

            var dataModelRepo = new DataModelRepository(targetService, prefixEnv);
            var statusEntries = new List<UploadStatusEntry>();
            var trackedTables = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var totalRows = allRows.Count;

            SetUploadProgress(10, $"Elaborazione 0/{totalRows}");

            for (var rowIndex = 0; rowIndex < totalRows; rowIndex++)
            {
                var taskRow = allRows[rowIndex];
                var row = taskRow.Row;
                if (row == null)
                {
                    UpdateProgressFromRow(rowIndex + 1, totalRows);
                    continue;
                }

                // Assumi: row = [System, Table, Schema name, Display name (IT), Display name (EN), Description, Column type, Lookup table, Additional data, Requirement level, Primary, Usage]
                var system = row.ElementAtOrDefault(0)?.Trim();
                var table = row.ElementAtOrDefault(1)?.Trim();
                var schemaName = row.ElementAtOrDefault(2)?.Trim();
                var displayNameIt = row.ElementAtOrDefault(3)?.Trim();
                var displayNameEn = row.ElementAtOrDefault(4)?.Trim();
                var description = row.ElementAtOrDefault(5)?.Trim();
                var columnType = row.ElementAtOrDefault(6)?.Trim();
                var lookupTable = row.ElementAtOrDefault(7)?.Trim();
                var additionalData = row.ElementAtOrDefault(8)?.Trim();
                var requirementLevel = row.ElementAtOrDefault(9)?.Trim();
                var usage = row.ElementAtOrDefault(11)?.Trim();
                var tableDisplayNameEn = taskRow.TableDisplayNameEn;
                var tableDisplayNameIt = taskRow.TableDisplayNameIt;

                if (string.IsNullOrWhiteSpace(table) || string.IsNullOrWhiteSpace(schemaName))
                {
                    statusEntries.Add(new UploadStatusEntry
                    {
                        Kind = "Column",
                        TableName = table,
                        ColumnName = schemaName,
                        Status = UploadResultStatus.Error,
                        ErrorMessage = "Table o Schema name mancante nel markdown"
                    });
                    UpdateProgressFromRow(rowIndex + 1, totalRows);
                    continue;
                }

                Entity tableEn = null;
                try
                {
                    var tableAlreadyExists = dataModelRepo.getTableByName(table).Entities.Any();

                    tableEn = dataModelRepo.GetOrCreateTable(
                        table,
                        system,
                        tableDisplayNameEn,
                        tableDisplayNameIt
                    );

                    if (!trackedTables.Contains(table))
                    {
                        statusEntries.Add(new UploadStatusEntry
                        {
                            Kind = "Table",
                            TableName = table,
                            Status = tableAlreadyExists ? UploadResultStatus.Existing : UploadResultStatus.Created
                        });
                        trackedTables.Add(table);
                    }
                }
                catch (Exception ex)
                {
                    if (!trackedTables.Contains(table))
                    {
                        statusEntries.Add(new UploadStatusEntry
                        {
                            Kind = "Table",
                            TableName = table,
                            Status = UploadResultStatus.Error,
                            ErrorMessage = ex.Message
                        });
                        trackedTables.Add(table);
                    }

                    statusEntries.Add(new UploadStatusEntry
                    {
                        Kind = "Column",
                        TableName = table,
                        ColumnName = schemaName,
                        Status = UploadResultStatus.Error,
                        ErrorMessage = $"Tabella non disponibile: {ex.Message}"
                    });
                    UpdateProgressFromRow(rowIndex + 1, totalRows);
                    continue;
                }

                if (tableEn == null)
                {
                    statusEntries.Add(new UploadStatusEntry
                    {
                        Kind = "Column",
                        TableName = table,
                        ColumnName = schemaName,
                        Status = UploadResultStatus.Error,
                        ErrorMessage = "Tabella non creata o non trovata"
                    });
                    UpdateProgressFromRow(rowIndex + 1, totalRows);
                    continue;
                }

                try
                {
                    var columnAlreadyExists = dataModelRepo.ColumnExists(schemaName, tableEn.Id);

                    var column = dataModelRepo.GetOrCreateColumn(
                        schemaName,
                        tableEn,
                        additionalData,
                        displayNameIt,
                        displayNameEn,
                        description,
                        columnType,
                        lookupTable,
                        requirementLevel,
                        usage);

                    statusEntries.Add(new UploadStatusEntry
                    {
                        Kind = "Column",
                        TableName = table,
                        ColumnName = schemaName,
                        Status = column != null
                            ? (columnAlreadyExists ? UploadResultStatus.Existing : UploadResultStatus.Created)
                            : UploadResultStatus.Error,
                        ErrorMessage = column == null ? "GetOrCreateColumn ha restituito null" : null
                    });
                }
                catch (Exception ex)
                {
                    statusEntries.Add(new UploadStatusEntry
                    {
                        Kind = "Column",
                        TableName = table,
                        ColumnName = schemaName,
                        Status = UploadResultStatus.Error,
                        ErrorMessage = ex.Message
                    });
                }

                UpdateProgressFromRow(rowIndex + 1, totalRows);
            }

            SetUploadProgress(98, "Generazione riepilogo");
            ShowUploadSummary(statusEntries);

            var hasErrors = statusEntries.Any(s => s.Status == UploadResultStatus.Error);
            if (hasErrors)
            {
                MessageBox.Show($"Upload su {targetName} completato con errori. Controlla il riepilogo nel pannello laterale.");
                return false;
            }

            SetUploadProgress(100, "Completato");
            MessageBox.Show($"Upload completato su {targetName}. Riepilogo disponibile nel pannello laterale.");
            return true;
        }

        private async Task<bool> UploadDataModelToEnvConnection(IOrganizationService targetService, string targetName, string solutionName)
        {
            if (targetService == null)
            {
                MessageBox.Show($"Connessione target non disponibile: {targetName}.");
                return false;
            }

            var prefixEnv = MarkdownUtilitiesService.NormalizePrefix(txtPrefix.Text);
            if (string.IsNullOrWhiteSpace(prefixEnv))
            {
                MessageBox.Show("Prefix mancante. Inserisci il prefix e salva le configurazioni.");
                return false;
            }

            var dataModelService = new DataModelService();
            var allRows = dataModelService.ParseDataModelMarkdown(txtMarkdown.Text, prefixEnv);
            if (allRows == null || allRows.Count == 0)
            {
                MessageBox.Show("Markdown vuoto o non valido. Premi Load Markdown e verifica il contenuto prima di caricare.");
                return false;
            }

            SetUploadProgress(5, "Validazione dati");
            var envRepo = new EnvironmentRepository(targetService, prefixEnv);
            if (!string.IsNullOrWhiteSpace(solutionName) && !envRepo.SolutionExists(solutionName))
            {
                MessageBox.Show($"La solution '{solutionName}' non esiste nell'ambiente target.");
                return false;
            }

            var statusEntries = new List<UploadStatusEntry>();
            var trackedTables = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var totalRows = allRows.Count;
            Dictionary<string, EnvironmentRepository.PrimaryAttributeDefinition> primaryAttributeByTable;
            var primaryColumnCreatedWithTable = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            try
            {
                primaryAttributeByTable = PrimaryAttributeResolverService.BuildPrimaryAttributeMap(allRows);
            }
            catch (InvalidOperationException ex)
            {
                MessageBox.Show(ex.Message);
                return false;
            }

            SetUploadProgress(10, $"Elaborazione 0/{totalRows}");

            for (var rowIndex = 0; rowIndex < totalRows; rowIndex++)
            {
                var taskRow = allRows[rowIndex];
                var row = taskRow.Row;
                if (row == null)
                {
                    UpdateProgressFromRow(rowIndex + 1, totalRows);
                    continue;
                }

                // Assumi: row = [System, Table, Schema name, Display name (IT), Display name (EN), Description, Column type, Lookup table, Additional data, Requirement level, Primary, Usage]
                var system = row.ElementAtOrDefault(0)?.Trim();
                var table = row.ElementAtOrDefault(1)?.Trim();
                var schemaName = row.ElementAtOrDefault(2)?.Trim();
                var displayNameIt = row.ElementAtOrDefault(3)?.Trim();
                var displayNameEn = row.ElementAtOrDefault(4)?.Trim();
                var description = row.ElementAtOrDefault(5)?.Trim();
                var columnType = row.ElementAtOrDefault(6)?.Trim();
                var lookupTable = row.ElementAtOrDefault(7)?.Trim();
                var additionalData = row.ElementAtOrDefault(8)?.Trim();
                var requirementLevel = row.ElementAtOrDefault(9)?.Trim();
                var usage = row.ElementAtOrDefault(11)?.Trim();
                var tableDisplayNameEn = taskRow.TableDisplayNameEn;
                var tableDisplayNameIt = taskRow.TableDisplayNameIt;

                if (string.IsNullOrWhiteSpace(table) || string.IsNullOrWhiteSpace(schemaName))
                {
                    statusEntries.Add(new UploadStatusEntry
                    {
                        Kind = "Column",
                        TableName = table,
                        ColumnName = schemaName,
                        Status = UploadResultStatus.Error,
                        ErrorMessage = "Table o Schema name mancante nel markdown"
                    });
                    UpdateProgressFromRow(rowIndex + 1, totalRows);
                    continue;
                }

                try
                {
                    var tableAlreadyExists = envRepo.TableExists(table);
                    if(!tableAlreadyExists)
                    {
                        primaryAttributeByTable.TryGetValue(table, out var primaryAttributeDefinition);
                        var normalizedPrimaryAttribute = (primaryAttributeDefinition?.SchemaName ?? $"{prefixEnv}name").Trim();

                        envRepo.CreateTable(
                            table,
                            system,
                            tableDisplayNameEn,
                            tableDisplayNameIt,
                            primaryAttributeDefinition
                        );

                        primaryColumnCreatedWithTable.Add($"{table.Trim().ToLowerInvariant()}|{normalizedPrimaryAttribute.Trim().ToLowerInvariant()}");

                        if (!string.IsNullOrWhiteSpace(solutionName))
                        {
                            envRepo.AddTableToSolution(solutionName, table);
                        }
                    }

                    if (!trackedTables.Contains(table))
                    {
                        statusEntries.Add(new UploadStatusEntry
                        {
                            Kind = "Table",
                            TableName = table,
                            Status = tableAlreadyExists ? UploadResultStatus.Existing : UploadResultStatus.Created
                        });
                        trackedTables.Add(table);
                    }
                }
                catch (Exception ex)
                {
                    if (!trackedTables.Contains(table))
                    {
                        statusEntries.Add(new UploadStatusEntry
                        {
                            Kind = "Table",
                            TableName = table,
                            Status = UploadResultStatus.Error,
                            ErrorMessage = ex.Message
                        });
                        trackedTables.Add(table);
                    }

                    statusEntries.Add(new UploadStatusEntry
                    {
                        Kind = "Column",
                        TableName = table,
                        ColumnName = schemaName,
                        Status = UploadResultStatus.Error,
                        ErrorMessage = $"Tabella non disponibile: {ex.Message}"
                    });
                    UpdateProgressFromRow(rowIndex + 1, totalRows);
                    continue;
                }

                try
                {
                    var normalizedKey = $"{table.Trim().ToLowerInvariant()}|{schemaName.Trim().ToLowerInvariant()}";
                    if (primaryColumnCreatedWithTable.Contains(normalizedKey))
                    {
                        statusEntries.Add(new UploadStatusEntry
                        {
                            Kind = "Column",
                            TableName = table,
                            ColumnName = schemaName,
                            Status = UploadResultStatus.Existing,
                            ErrorMessage = "Colonna primaria gia creata durante CreateTable"
                        });

                        UpdateProgressFromRow(rowIndex + 1, totalRows);
                        continue;
                    }

                    var columnAlreadyExists = envRepo.ColumnExists(schemaName, table);

                    var column = envRepo.GetOrCreateColumn(
                        schemaName,
                        table,
                        additionalData,
                        displayNameIt,
                        displayNameEn,
                        description,
                        columnType,
                        lookupTable,
                        requirementLevel,
                        usage);

                    if (!columnAlreadyExists && !string.IsNullOrWhiteSpace(solutionName))
                    {
                        envRepo.AddColumnToSolution(solutionName, table, schemaName);
                    }

                    statusEntries.Add(new UploadStatusEntry
                    {
                        Kind = "Column",
                        TableName = table,
                        ColumnName = schemaName,
                        Status = column != null
                            ? (columnAlreadyExists ? UploadResultStatus.Existing : UploadResultStatus.Created)
                            : UploadResultStatus.Error,
                        ErrorMessage = column == null ? "GetOrCreateColumn ha restituito null" : null
                    });
                }
                catch (Exception ex)
                {
                    statusEntries.Add(new UploadStatusEntry
                    {
                        Kind = "Column",
                        TableName = table,
                        ColumnName = schemaName,
                        Status = UploadResultStatus.Error,
                        ErrorMessage = ex.Message
                    });
                }

                UpdateProgressFromRow(rowIndex + 1, totalRows);
            }

            SetUploadProgress(98, "Generazione riepilogo");
            ShowUploadSummary(statusEntries);

            var hasErrors = statusEntries.Any(s => s.Status == UploadResultStatus.Error);
            if (hasErrors)
            {
                MessageBox.Show($"Upload su {targetName} completato con errori. Controlla il riepilogo nel pannello laterale.");
                return false;
            }

            SetUploadProgress(100, "Completato");
            MessageBox.Show($"Upload completato su {targetName}. Riepilogo disponibile nel pannello laterale.");
            return true;
        }

        private void ResetUploadProgress()
        {
            uploadProgressService?.Reset();
        }

        private void HideUploadProgressForOtherAction()
        {
            uploadProgressService?.HideForOtherAction();
        }

        private void SetUploadProgress(int percentage, string step)
        {
            uploadProgressService?.SetProgress(percentage, step);
        }

        private void UpdateProgressFromRow(int currentRow, int totalRows)
        {
            uploadProgressService?.UpdateFromRow(currentRow, totalRows);
        }

        private void ShowUploadSummary(List<UploadStatusEntry> statuses)
        {
            UploadSummaryService.ShowSummary(txtUploadSummary, lblUploadSummary, statuses);
        }

        private void HideUploadSummary()
        {
            UploadSummaryService.HideSummary(txtUploadSummary, lblUploadSummary);
        }

        private async void buttonLoadMarkdown_Click(object sender, EventArgs e)
        {
            HideUploadProgressForOtherAction();
            HideUploadSummary();
            buttonLoadMarkdown.Enabled = false;
            try
            {
                var prefixEnv = MarkdownUtilitiesService.NormalizePrefix(txtPrefix.Text);
                if (string.IsNullOrWhiteSpace(prefixEnv))
                {
                    MessageBox.Show("Prefix mancante. Inserisci il prefix e salva le configurazioni.");
                    return;
                }

                var dataModelService = new DataModelService();
                var markdown = await dataModelService.getDataModelMarkdown(
                    txtConnectionString.Text.Trim(),
                    prefixEnv,
                    txtTaskIds.Text.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                );

                if (string.IsNullOrWhiteSpace(markdown))
                {
                    MessageBox.Show("Nessun contenuto trovato dai task indicati.");
                    return;
                }

                txtMarkdown.Text = markdown;
                isMarkdownTemplateAutoGenerated = false;
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Errore nel caricamento markdown: {ex.Message}");
            }
            finally
            {
                buttonLoadMarkdown.Enabled = true;
            }
        }

        private async void buttonCreateTask_Click(object sender, EventArgs e)
        {
            HideUploadProgressForOtherAction();
            HideUploadSummary();

            if (!CanStartUploadWithCurrentMarkdown())
            {
                return;
            }

            if (string.IsNullOrWhiteSpace(txtConnectionString.Text))
            {
                MessageBox.Show("Connection string DevOps mancante. Inseriscila prima di creare il task.");
                return;
            }

            if (!int.TryParse((txtParentTaskId.Text ?? string.Empty).Trim(), out var parentTaskId) || parentTaskId <= 0)
            {
                MessageBox.Show("Inserisci un Parent Task ID valido (numero intero positivo).");
                return;
            }

            var markdown = (txtMarkdown.Text ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(markdown))
            {
                MessageBox.Show("Markdown vuoto. Compila o carica il markdown prima di creare il task.");
                return;
            }

            buttonCreateTask.Enabled = false;
            try
            {
                var entityName = MarkdownUtilitiesService.ExtractEntityNameFromMarkdown(markdown);
                var title = $"[D365] - Modifica DATA MODEL entita {entityName}";

                var repo = new DevOpsRepository(txtConnectionString.Text.Trim());
                var createdTask = await repo.CreateChildTaskAsync(parentTaskId, title, markdown);

                MessageBox.Show($"Task creato correttamente: ID {createdTask?.Id}");
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Errore nella creazione del task: {ex.Message}");
            }
            finally
            {
                buttonCreateTask.Enabled = true;
            }
        }

        private async void PluginControl_Load(object sender, EventArgs e)
        {
            UpdateMainConnectionButtonLabel();
            await TryPopulateMarkdownTemplateFromPrimaryConnectionAsync();
        }

        private void UpdateMainConnectionButtonLabel()
        {
            var mainConnName = this.ConnectionDetail?.ConnectionName ?? "Env";
            buttonUploadAmbiente.Text = $"Upload to {mainConnName}";
        }

        private async Task TryPopulateMarkdownTemplateFromPrimaryConnectionAsync()
        {
            if (Service == null)
            {
                return;
            }

            try
            {
                var markdownTemplate = await Task.Run(() => MarkdownUtilitiesService.BuildMarkdownTemplateFromPrimaryConnectionLanguages(Service));
                if (string.IsNullOrWhiteSpace(markdownTemplate))
                {
                    return;
                }

                if (txtMarkdown.InvokeRequired)
                {
                    txtMarkdown.Invoke(new Action(() => ApplyGeneratedMarkdownTemplate(markdownTemplate)));
                }
                else
                {
                    ApplyGeneratedMarkdownTemplate(markdownTemplate);
                }
            }
            catch
            {
                // Non blocchiamo il caricamento del plugin se la retrieve lingue fallisce.
            }
        }

        private void ApplyGeneratedMarkdownTemplate(string markdownTemplate)
        {
            var current = txtMarkdown.Text ?? string.Empty;
            if (string.IsNullOrWhiteSpace(current) || (isMarkdownTemplateAutoGenerated && string.Equals(current, lastGeneratedMarkdownTemplate, StringComparison.Ordinal)))
            {
                txtMarkdown.Text = markdownTemplate;
                lastGeneratedMarkdownTemplate = markdownTemplate;
                isMarkdownTemplateAutoGenerated = true;
            }
        }

        private bool CanStartUploadWithCurrentMarkdown()
        {
            var current = MarkdownUtilitiesService.NormalizeForComparison(txtMarkdown.Text);
            var autoTemplate = MarkdownUtilitiesService.NormalizeForComparison(lastGeneratedMarkdownTemplate);

            var isDefaultAutoTemplate = !string.IsNullOrWhiteSpace(autoTemplate) &&
                string.Equals(current, autoTemplate, StringComparison.Ordinal);

            if (!isDefaultAutoTemplate)
            {
                return true;
            }

            MessageBox.Show(
                "Il markdown contiene ancora lo schema di default precompilato. Compila i dati reali oppure usa 'Load Markdown' prima di eseguire l'upload.",
                "Warning",
                MessageBoxButtons.OK,
                MessageBoxIcon.Warning);

            return false;
        }

	}
}
